### ISSUE TITLE
No diff shown with JsonAssert.Equal..

### ISSUE THREAD

**Issue by lilith** [weichch/system-text-json-jsondiffpatch#44]
[xUnit.net 00:00:00.32]     Imageflow.Test.TestJson.TestAllJob [FAIL]
  Failed Imageflow.Test.TestJson.TestAllJob [186 ms]
  Error Message:
   System.Text.Json.JsonDiffPatch.Xunit.JsonEqualException : JsonAssert.Equal() failure.
  Stack Trace:
     at System.Text.Json.JsonDiffPatch.Xunit.JsonAssert.HandleEqual(JsonNode expected, JsonNode actual, JsonDiffOptions diffOptions, Func`2 outputFormatter)
   at System.Text.Json.JsonDiffPatch.Xunit.JsonAssert.Equal[T](T expected, T actual)
   at Imageflow.Test.TestJson.TestAllJob() in C:\Users\lilith\Documents\GitHub\wimageflow-dotnet\tests\Imageflow.Test\TestJson.cs:line 70
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by meastp** [comment]
@lilith I had the same issue. There are overloads of the function(s) that take a boolean parameter that controls if the diff should be shown. This is missing from the readme.
